2021-10-12 16:57:33,089 | INFO -> O programa foi iniciado
2021-10-12 16:57:33,350 | DEBUG -> Iteração número 0
2021-10-12 16:57:33,365 | ERROR -> Erro não esperado ->invalid literal for int() with base 10: "logger.info('O programa foi finalizado')"
2021-10-12 16:57:33,365 | DEBUG -> Iteração número 1
2021-10-12 16:57:36,580 | DEBUG -> O usuário digitou o primeiro número: 10
2021-10-12 16:57:39,932 | DEBUG -> O usuário digitou o segundo número: 0
2021-10-12 16:57:39,933 | WARNING -> O usuário tentou fazer uma divisão por 0
2021-10-12 16:57:39,934 | DEBUG -> Iteração número 2
2021-10-12 16:57:43,185 | DEBUG -> O usuário digitou o primeiro número: 12
2021-10-12 16:57:43,554 | DEBUG -> O usuário digitou o segundo número: 2
2021-10-12 16:57:43,561 | DEBUG -> O resultado da operação: 6.0
2021-10-12 16:59:23,192 | INFO -> O programa foi iniciado
2021-10-12 16:59:23,451 | DEBUG -> Iteração número 0
2021-10-12 16:59:23,465 | ERROR -> Erro não esperado -> invalid literal for int() with base 10: "logger.info('O programa foi finalizado')"
2021-10-12 16:59:23,466 | DEBUG -> Iteração número 1
2021-10-12 16:59:26,800 | DEBUG -> O usuário digitou o primeiro número: 10
2021-10-12 16:59:29,502 | DEBUG -> O usuário digitou o segundo número: 0
2021-10-12 16:59:29,502 | WARNING -> O usuário tentou fazer uma divisão por 0
2021-10-12 16:59:29,502 | DEBUG -> Iteração número 2
2021-10-12 16:59:33,665 | ERROR -> Erro não esperado -> invalid literal for int() with base 10: 'a'
